"""initial schema

Revision ID: 396dbfc88234
Revises:
Create Date: 2026-07-25 22:21:42.878219
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "396dbfc88234"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cars",
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("marca", sa.String(), nullable=False),
        sa.Column("linea", sa.String(), nullable=False),
        sa.Column("modelo", sa.Integer(), nullable=False),
        sa.Column("km", sa.String(), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("matricula", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("transmision", sa.String(), nullable=False),
        sa.Column("combustible", sa.String(), nullable=False),
        sa.Column("cilindraje", sa.String(), nullable=False),
        sa.Column("traccion", sa.String(), nullable=False),
        sa.Column("direccion", sa.String(), nullable=False),
        sa.Column("frenos", sa.String(), nullable=False),
        sa.Column("airbag", sa.String(), nullable=False),
        sa.Column("placa", sa.String(), nullable=False),
        sa.Column("vin", sa.String(), nullable=True),
        sa.Column("chasis_no", sa.String(), nullable=True),
        sa.Column("motor_no", sa.String(), nullable=True),
        sa.Column("importacion_no", sa.String(), nullable=True),
        sa.Column("importacion_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ALMACEN", "VENDIDO", "OFERTADO", "OCULTO", name="car_status"),
            nullable=False,
        ),
        sa.Column("consignacion", sa.Boolean(), nullable=False),
        sa.Column("featured", sa.Boolean(), nullable=False),
        sa.Column("images", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("price >= 0", name="ck_cars_price_non_negative"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "interes_forms",
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("apellido", sa.String(), nullable=False),
        sa.Column("celular", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("wpp_check", sa.Boolean(), nullable=False),
        sa.Column("marca", sa.String(), nullable=False),
        sa.Column("linea", sa.String(), nullable=False),
        sa.Column("modelo", sa.Integer(), nullable=False),
        sa.Column("km", sa.String(), nullable=False),
        sa.Column("price", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ofertas_forms",
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("apellido", sa.String(), nullable=False),
        sa.Column("celular", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("wpp_check", sa.Boolean(), nullable=False),
        sa.Column("marca", sa.String(), nullable=False),
        sa.Column("linea", sa.String(), nullable=False),
        sa.Column("modelo", sa.Integer(), nullable=False),
        sa.Column("km", sa.String(), nullable=False),
        sa.Column("matricula", sa.String(), nullable=False),
        sa.Column("price", sa.String(), nullable=False),
        sa.Column("images", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("firstname", sa.String(), nullable=False),
        sa.Column("lastname", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "vehiculos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("marca", sa.String(), nullable=False),
        sa.Column("linea", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("motor", sa.String(), nullable=True),
        sa.Column("fabricacion", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tipo", "marca", "linea", "version", name="uq_vehiculos_catalog_entry"),
    )
    op.create_index(op.f("ix_vehiculos_marca"), "vehiculos", ["marca"], unique=False)
    op.create_index(op.f("ix_vehiculos_tipo"), "vehiculos", ["tipo"], unique=False)
    op.create_table(
        "compra_forms",
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("apellido", sa.String(), nullable=False),
        sa.Column("celular", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("cedula", sa.String(), nullable=False),
        sa.Column("wpp_check", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("car_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["car_id"], ["cars.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plate_searches",
        sa.Column("plate", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("simit_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fasecolda_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plate", "user_id", name="uq_plate_searches_plate_user"),
    )
    op.create_table(
        "tramites",
        sa.Column("tramitador", sa.String(), nullable=False),
        sa.Column("celular", sa.String(), nullable=False),
        sa.Column(
            "fecha_inicio",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_fin", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estado", sa.String(), nullable=False),
        sa.Column("documentos", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("observaciones", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("precio", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("car_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["car_id"], ["cars.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tramites")
    op.drop_table("plate_searches")
    op.drop_table("compra_forms")
    op.drop_index(op.f("ix_vehiculos_tipo"), table_name="vehiculos")
    op.drop_index(op.f("ix_vehiculos_marca"), table_name="vehiculos")
    op.drop_table("vehiculos")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_table("ofertas_forms")
    op.drop_table("interes_forms")
    op.drop_table("cars")
    # ### end Alembic commands ###
